### ISSUE TITLE
draft filters on main entity

### ISSUE THREAD

**Issue by chholzer1190** [RizInno/cdsx-samples#1]
Hi Jhodel,
this is a very interesting library.
Unfortunately I seem to have an issue.
1) I have imported an edmx creatting a file PaPmSalesData.csn with
{
    "meta": {
     "creator": "cds-dk 7.4.1"
    },
    "$version": "2.0",
    "definitions": {
     "PaPmSalesData": {
      "kind": "service",
      "@cds.external": true,
      "@m.IsDefaultEntityContainer": "true",
      "@sap.message.scope.supported": "true",
      "@sap.supported.formats": "atom json xlsx"
     },
     "PaPmSalesData.ZPAPM_DYP_SD_CDS": {
      "kind": "entity",
      "@cds.external": true,
      "@cds.persistence.skip": true,
....
2) I added in package.json
    "cds": {
        "requires": {
            "PaPmSalesData": {
                "kind": "odata-v2",
                "model": "srv/external/PaPmSalesData",
                }
            },
3) then I created the schema.cds file
context md {
    @cdsx.api : 'PaPmSalesData'
    
    entity ZPAPM_DYP_SD_CDS {
        @cdsx.object.key
            key FS_PER_GUID_: cds.UUID;
            SALES_ID: String(12);
            CSP_IACC: String(15);
            YDP_NAME: String(60);
            CSP_PRID: String(15);
            CSP_STAT: String(15);
            CSP_STAD: String(25);
            CSP_VDAT: cds.Date;
            CSP_BDAT: cds.Date;
            CSP_PAMT: Decimal(15);
    }
}
4) Then I created a file salesdata-service.cds
using {md} from '../db/schema';

service SalesdataService {

    @odata.draft.enabled
    entity SalesData as projection on md.ZPAPM_DYP_SD_CDS 
}
5) In salesdata-service.js I added
const cds = require('@sap/cds');
const cdsx = require("@rizing/cds-extension");
const { default: test } = require('node:test');

cds.on("bootstrap", (app) => {
	cdsx.load();
});

module.exports = cds.service.impl(async function() {
	const { SalesData } = this.entities;
	const service = await cds.connect.to('PaPmSalesData');
	this.on('READ', SalesData, request => {
		return service.tx(request).run(request.query);
	});

Now when I run the fiori ListReport and call READ for this service, I do not get any result.
When I set a breakpoint for READ of the SalesData and look into the request.filter I see "(IsActiveEntity) eq false or SiblingEntity/IsActiveEntity eq null". But this filter should only be there for SalesData.draft, shouldn't it?
What am I missing?

BR Christian

**Comment by chholzer1190** [comment]
So I did a little howmework: But now I get the error message "Bad gateway".

When I look into the logs, I see the follwoing trace:
"msg":"context.getUrlObject is not a function",
"stacktrace":["TypeError: context.getUrlObject is not a function",
"at Object.reject (/home/vcap/app/node_modules/@rizing/cds-extension/lib/util/cdsx.js:97:41)",
"at module.exports (/home/vcap/app/node_modules/@rizing/cds-extension/lib/crud/read.js:215:8)",
"at next (/home/vcap/app/node_modules/@sap/cds/lib/srv/srv-dispatch.js:79:36)",
"at ApplicationService.handle (/home/vcap/app/node_modules/@sap/cds/lib/srv/srv-dispatch.js:83:6)",
"at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
"at async Promise.all (index 0)","at async all (/home/vcap/app/node_modules/@sap/cds/libx/_runtime/fiori/lean-draft.js:543:34)",
"at async cds.ApplicationService.handle (/home/vcap/app/node_modules/@sap/cds/libx/_runtime/fiori/lean-draft.js:201:20)",
"at async _readCollection (/home/vcap/app/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/handlers/read.js:249:19)",
"at async /home/vcap/app/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/handlers/read.js:480:16"],"id":"1598741",

BR Christian

**Comment by ulyssesb** [comment]
The package doesn't seem to compatible with @sap/cds ^7 due to lean drafts, where a separate entity was introduce to handle drafts (BusinessPartner.draft).

Lean draft features might overlap with @rizing/cds-extension, but they seem not production-ready. Documentation is scarce, with only a comment [here](https://community.sap.com/t5/technology-blogs-by-members/keep-the-core-clean-with-rizing-cdsx/ba-p/13548344) and a reference [video](https://www.youtube.com/watch?v=FvwNFCiFADw).

To address this issue, a potential workaround is to `npm i -P @sap/cds@6.8.4`, but downgrading could be a significant task depending on your project.

**Comment by sammok83** [comment]
> The package doesn't seem to compatible with @sap/cds ^7 due to lean drafts, where a separate entity was introduce to handle drafts (BusinessPartner.draft).
> 
> Lean draft features might overlap with @rizing/cds-extension, but they seem not production-ready. Documentation is scarce, with only a comment [here](https://community.sap.com/t5/technology-blogs-by-members/keep-the-core-clean-with-rizing-cdsx/ba-p/13548344) and a reference [video](https://www.youtube.com/watch?v=FvwNFCiFADw).
> 
> To address this issue, a potential workaround is to `npm i -P @sap/cds@6.8.4`, but downgrading could be a significant task depending on your project.

@ulyssesb Did you implement any workarounds for the latest cds versions?
